[package]
name = "cc_fw"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cc_fw"
test = false
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
